version: 2

jobs:
  test: &test
    working_directory: /home/sage/henselization
    docker:
      - image: sagemath/sagemath:latest
    steps:
      - checkout
      - run:
          name: sage -tp
          no_output_timeout: 30m
          command: |
            sudo apt-get update && sudo apt-get install -y ca-certificates
            sage -pip install patchy
            sage -python setup.py install
            sage -tp --long --initial henselization
  "test-sage-9.3":
    <<: *test
    docker:
      - image: sagemath/sagemath:9.3
  "test-sage-9.4":
    <<: *test
    docker:
      - image: sagemath/sagemath:9.4
  "test-sage-10.1":
    <<: *test
    docker:
      - image: sagemath/sagemath:10.1
  pyflakes:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: pyflakes
          command: |
            pip install pyflakes
            find henselization -name '*.py' -not -name '__init__.py' | xargs pyflakes
  docbuild-sage:
    docker:
      - image: sagemath/sagemath:latest
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update && sudo apt-get install -y build-essential ca-certificates
            sage -pip install patchy
            sage -python setup.py install
            cd docs
            mkdir -p _static
            sage -sh -c 'make html SPHINXOPTS="-W"'
  docbuild-readthedocs:
    docker:
      - image: readthedocs/build
    steps:
      - checkout
      - run:
          command: |
            set -exo pipefail
            pip install --user readthedocs-build
            mkdir -p docs/_static
            ~/.local/bin/rtd-build 2>&1 | tee /tmp/rtd.log
            # fail on warnings
            grep WARNING /tmp/rtd.log && false
            # check that readthedocs produced something non-empty
            (( $(du -s _readthedocs_build/henselization/html | cut -f1) > 500 ))

workflows:
  version: 2
  test:
    jobs:
       # When adding a new stable release of Sage here, make sure to also upgrade the Dockerfile
       - test-sage-9.3
       - test-sage-9.4
       - test-sage-10.1
       - pyflakes
       - docbuild-sage
       - docbuild-readthedocs
